Vagrant.configure(2) do |config|
  config.vm.box = 'esxi-6.7-amd64'
  config.vm.hostname = 'example.test'

  config.vm.provider 'libvirt' do |lv, config|
    lv.memory = 4096
    lv.cpus = 4
  end

  # NB you must use `privileged: false` in the provisioning septs because esxi
  #    does not have the `sudo` command, and, by default, you are already
  #    executing commands as root.

  # do not Join the VMware Customer Experience Improvement Program.
  config.vm.provision :shell, privileged: false, inline: 'esxcli system settings advanced set -o /UserVars/HostClientCEIPOptIn -i 2'
  # show the ESXi version.
  config.vm.provision :shell, privileged: false, inline: 'esxcli system version get'
end
