Vagrant.configure(2) do |config|
  config.vm.box = 'esxi-6.7-amd64'

  config.vm.provider 'libvirt' do |lv, config|
    lv.memory = 4096
    lv.cpus = 4
  end

  config.vm.provision 'shell', inline: 'esxcli system version get', privileged: false
end
